fn call_with_five(f: fn(i32) -> i32) {
    println!("Fn pointer call: {}", f(5));
}

fn main() {
    // 1. Function pointer to a standard function
    fn add_one(x: i32) -> i32 { x + 1 }
    call_with_five(add_one);
    
    // 2. Closure capturing environment
    let coefficient = 10;
    let closure = |x| x * coefficient;
    
    // call_with_five(closure); // Error! Closure with state cannot be coerced to a plain fn pointer.
    println!("Closure call: {}", closure(5));
}

// ! **Function Pointers and Closures**
// ! - Function pointer `fn` is a "thin" pointer: it stores only the machine code memory address.
// ! - Closure (anonymous function) can capture external variables and carry payload state.
// ! - Closures receive a unique anonymous type generated by the compiler.

// ---

fn call_fn<F: Fn()>(f: F) { f(); }
fn call_fn_mut<F: FnMut()>(mut f: F) { f(); }
fn call_fn_once<F: FnOnce()>(f: F) { f(); }

fn main() {
    let mut greeting = "Hello".to_string();
    
    // Fn: only reads environment
    let closure_fn = || println!("Fn: {}", greeting);
    call_fn(closure_fn);
    
    // FnMut: mutates environment
    let closure_mut = || {
        greeting.push_str(" World");
        println!("FnMut: {}", greeting);
    };
    call_fn_mut(closure_mut);
    
    // FnOnce: consumes (moves) ownership of greeting
    let closure_once = move || {
        let consumed = greeting;
        println!("FnOnce: {}", consumed);
    };
    call_fn_once(closure_once);
    // call_fn_once(closure_once); // Error! Variable closure_once was already consumed.
}

// ! **Traits Fn, FnMut, and FnOnce**
// ! - `Fn`: captures via shared reference `&self`. Allows concurrent multi-threaded execution.
// ! - `FnMut`: captures via exclusive reference `&mut self`. Allows mutating captured state.
// ! - `FnOnce`: consumes captured state. Can be called exactly once.

// ---

fn get_counter(mut start: u32) -> impl FnMut() -> u32 {
    move || {
        start += 1;
        start
    }
}

fn main() {
    let mut next = get_counter(100);
    println!("Counter: {}", next());
    println!("Counter: {}", next());
}

// ! **Returning Closures from Functions**
// ! - Because closure types are anonymous, we use `impl Trait` return position syntax.
// ! - We must use the `move` keyword to transfer ownership of captured variables.
// ! - Otherwise the returned closure would reference local variables destroyed upon function exit.

// ---

// ?hidden:start
fn process_borrowed<F>(f: F)
where
    F: for<'a> Fn(&'a str),
{
    let local_string = String::from("Local Data");
    f(&local_string); // Reference lives strictly inside function
}
// ?hidden:end

fn main() {
    // Closure accepts a string slice whose lifetime is determined inside process_borrowed
    let print_len = |s: &str| println!("String length: {}", s.len());
    process_borrowed(print_len);
}
